server:
  port: 9999

spring:
  application:
    name: user-service
  profiles:
    include: common,kafka
#    properties:
##      hibernate:
##        default_schema: youzheng_web
##        dialect: org.hibernate.dialect.MySQL8Dialect
##        format_sql: true
##        jdbc:
##          batch_size: 500
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
    datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL

---